chart:
  name: zookeeper
replicaCount: 1

image:
  repository: wurstmeister/zookeeper
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 2181

env:
  ZOOKEEPER_CLIENT_PORT: 2181
  ZOOKEEPER_TICK_TIME: 2000

resources:
  requests:
    memory: "256Mi"
  limits:
    memory: "512Mi"

ingress:
  ip: "172.205.94.46"


