apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart.name }}
  labels:
    app: {{ .Values.chart.name }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.port}}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
    {{- if and (eq .Values.service.type "NodePort") .Values.service.nodePort}}
    nodePort: {{ .Values.service.nodePort }}
    {{- end }}
  {{- end}}
  selector:
    app: {{ .Values.chart.name }}
