apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart.name }}-broker
  labels:
    app: {{ .Values.chart.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  {{- range .Values.service.ports }}
  - name: {{ .name }}
    protocol: TCP
    port: {{ .value }}
    targetPort: {{ .value }}
  {{- end }}
  selector:
    app: {{ .Values.chart.name }}
