chart:
  name: notification-service
replicaCount: 1

image:
  repository: linkedinmsacr.azurecr.io/notification-service
  tag: "1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9060

volume:
  name: services-volume
  mountPath: /notification-service
  persistentVolumeClaim: notification-service-pvc
  storage: 500Mi

resources:
  requests:
    memory: "256Mi"
  limits:
    memory: "512Mi"

env:
  SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/postsDB
  SPRING_DATASOURCE_USERNAME: root
  SPRING_DATASOURCE_PASSWORD: root
  KAFKA_BOOTSTRAP_SERVERS: kafka-broker:9092