apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-token-secret
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: {{ .Values.serviceAccountName }}
type: kubernetes.io/service-account-token
