apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chart.name }}
  labels:
    app: {{ .Values.chart.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - protocol: TCP
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.port }}
  selector:
    app: {{ .Values.chart.name }}
