chart:
  name: connections-service
replicaCount: 1

image:
  repository: linkedinmsacr.azurecr.io/connections-service
  tag: "1"
  pullPolicy: Always

service:
  type: ClusterIP
  port: 9030

volume:
  name: services-volume
  mountPath: /connections-service
  persistentVolumeClaim: connections-service-pvc
  storage: 500Mi

resources:
  requests:
    memory: "256Mi"
  limits:
    memory: "512Mi"